require("@rails/ujs").start();
require("turbolinks").start();
require("@rails/activestorage").start();
require("channels");
require("styles");
require("popper.js");
require("bootstrap");
// require("works");
require("jquery");
require("works");
